### ISSUE TITLE
overwrite existing build status

### ISSUE THREAD

**Issue by 030** [030/bcbsn#20]
https://developer.atlassian.com/server/bitbucket/how-tos/updating-build-status-for-commits/

Updating build results

Bitbucket Server stores one build result for each key per commit, so you can update a previous build result by sending a request with:

    the same commit hash; and
    the same key attribute.

**Comment by jorianvo** [comment]
Since we are currently using the Jenkins Build ID as key, if you add a commit to your branch a new build will be triggered (hence you get a new key). And Bitbucket see it as a new status (i.e. you sometimes cannot merge).

**Comment by 030** [comment]
@jorianvo using the same value, e.g. git_commit_hash for commit and key solved the issue.
